FROM postgres:latest

# Set environment variables
ENV POSTGRES_PASSWORD=rootroot
ENV POSTGRES_DB=testdb
ENV POSTGRES_USER=root

# Set the exposed port
EXPOSE 5432

# Set the command for running the database
CMD ["postgres"]

