@startuml blogging-landscape
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(client, "Usuario", "Cliente de la aplicación 'IWPhone'")
System_Boundary(c1, "Sistema") {
    Container(teleoperator, "Sistema teleoperadora", "Sistema Software", "Permite a los usuarios modificar sus contratos, servicios y mostrar sus facturas")
    Container(email, "Sistema E-mail", "Sistema Software", "Sistema interno de mensajería electrónica")
    Container(mainframe, "Mainframe", "Sistema Software", "Almacena la información de la teleoperadora como la información de los usuarios, los contratos, los servicios, etc.")
    Person(backoffice, "Personal del Back-Office", "Administración y equipo de soporte del personal")
}
Rel(teleoperator, email, "Envía e-mails")
Rel(email, client, "Envía e-mails a")
Rel(teleoperator, mainframe, "Recibe la información de los contratos, servicios, etc.")
Rel(client, teleoperator, "Gestión de contratación y consulta de consumos")
Rel(backoffice, mainframe, "Usa")
@enduml